### PR TITLE
docs: Add module documentation for 'containerfile' and 'files'

### PR DESCRIPTION
**Pull request by gmpinder**

### CODE REVIEW

**Comment by fiftydinar** [comment]
This looks good!

Should we depreciate bash `files` module for this one?
What is the plan for that?

**Comment by gmpinder** [comment]
> This looks good!
> 
> Should we depreciate bash `files` module for this one? What is the plan for that?

I think we should since we aren't using any of the bash from that module.

**Comment by xynydev** [comment]
I'm not sure about including the files module docs here, because the bash module will be kept alive too, but the docs here are essentially the same.

Will review other docs more closely later today.

**Comment by xynydev** [comment]
I opted to put the `files` module docs only here instead, removing the docs from the bash modules repo.

**Pull request merged**
