### PR TITLE
chore: Copy signing keys to `/etc/` only

### PR DESCRIPTION
**Pull request by fiftydinar**
Supplements main PR: https://github.com/blue-build/modules/pull/375

Tests & it works, can be merged.

### CODE REVIEW

**Review by gmpinder — APPROVED** [review]
The changes look good, but it seems like the signing module is causing failures. I think that will have to be updated before this can be merged in.

**Comment by fiftydinar** [comment]
> The changes look good, but it seems like the signing module is causing failures. I think that will have to be updated before this can be merged in.

Hmm, error implies that keys are not copied to `/etc/pki/containers/`.

Maybe that's only in Ublue image. I would like to know if that issue is gone in vanilla Fedora based images.

**Comment by fiftydinar** [comment]
It would be good to use the `signing` module from my PR temporarily to test this, then revert it back.
Is that good?

**Comment by fiftydinar** [comment]
> It would be good to use the `signing` module from my PR temporarily to test this, then revert it back. Is that good?

I confirm it works now.

**Review by xynydev — APPROVED** [review]

**Review by gmpinder — APPROVED** [review]

**Comment by gmpinder** [comment]
> > It would be good to use the `signing` module from my PR temporarily to test this, then revert it back. Is that good?
> 
> I confirm it works now, so it can be merged.

I'm not comfortable merging this in until https://github.com/blue-build/modules/pull/375 is merged. I run my builds of the `main` branch and this will fail them without the module changes.

**Comment by fiftydinar** [comment]
> > > It would be good to use the `signing` module from my PR temporarily to test this, then revert it back. Is that good?
> > 
> > 
> > I confirm it works now, so it can be merged.
> 
> I'm not comfortable merging this in until [blue-build/modules#375](https://github.com/blue-build/modules/pull/375) is merged. I run my builds of the `main` branch and this will fail them without the module changes.

Merged

**Pull request merged**
