### PR TITLE
fix: address akmods latest bug

### PR DESCRIPTION
**Pull request by bayou-brogrammer**
Akmods do not support the latest tag. This just sets it to 39 if they have latest in their system

### CODE REVIEW

**Review by xynydev — APPROVED** [review]

**Comment by fiftydinar** [comment]
The issue with this is that it's not dynamic, you would need to change this every time new Fedora release comes in.

**Comment by bayou-brogrammer** [comment]
> The issue with this is that it's not dynamic, you would need to change this every time new Fedora release comes in.

it is not meant to be dynamic. I think its ok to have hardcoded values. We can just come back and revisit this on the next release. Releases happen on a ~6month cadence.

**Comment by bayou-brogrammer** [comment]
it is not meant to be dynamic. I think its ok to have hardcoded values. We
can just come back and revisit this on the next release. Releases happen on
a ~6month cadence.

**Comment by gmpinder** [comment]
We get the OS version from labels. Is there a reason why that's not working for you? I'm with @fiftydinar on this, we shouldn't hard code this in and instead find a more reliable way to get the information we need

**Review by xynydev — CHANGES_REQUESTED** [review]
Ok, yeah, I didn't look at it so closely. I agree.

**Comment by fiftydinar** [comment]
@bayou-brogrammer it would be maybe a good idea to land last "default to main" fix in a separate PR.

**Comment by bayou-brogrammer** [comment]
> @bayou-brogrammer it would be maybe a good idea to land last "default to main" fix in a separate PR.

crap didnt realize i was still on this branch

**Pull request closed without merging**
