### PR TITLE
fix: allow empty custom modules dir

### PR DESCRIPTION
**Pull request by qoijjj**

### CODE REVIEW

**Comment by gmpinder** [comment]
This won't work like you expect. Create an issue and I'll get a fix in for you tonight.

**Comment by qoijjj** [comment]
Doing so now. Out of curiosity, why won't this work?

**Comment by qoijjj** [comment]
https://github.com/blue-build/cli/issues/78

**Comment by xynydev** [comment]
> Out of curiosity, why won't this work?

The COPY command copies from outside the container to inside the container. The RUN command only works inside the container. So basically, this change would create a modules directory inside the container, then copy the modules directory from outside the container to inside the container.

**Review by gmpinder — APPROVED** [review]

**Pull request merged**
